name: Docker image (build/publish)

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - docs
      - config-pipeline


jobs:
  build-and-deploy-docker:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Genere jar
        run: mvn package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/estebanbrnd/projetdevops:latest  
