name: Run tests before merging

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches: 
      - docs


jobs:
  tests-check:
    name: Tests check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Execution des tests
        run: mvn test
  deploy-readme:
    name: ReadMe => GitHub Pages
    needs: tests-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Copie de ReadMe
        run: cp README.md ./docs/index.md

      - name: Deploiement sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
  

