name: Execution des tests

on: 
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - docs
      - config-pipeline


jobs:
  tests-check:
    name: Tests check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Execution des tests
        run: mvn test
  more-tests:
    name: Plus de tests
    needs: tests-check

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Check code coverage
        run: mvn verify
  
      - name: Generate JaCoCo report
        run: mvn jacoco:report
