name: Execution dans le Cloud

jobs:
  terraform:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set credentials as environment variable
      run: |
        cd ./terraform
        echo "$CREDENTIALS" > mycredentials.json
      env:
        MY_CREDENTIALS_JSON: ${{ secrets.CREDENTIALS }}

    - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          backend-config: '${{ secrets.CREDENTIALS }}'
          working-directory: ./terraform


      - name: Terraform apply
        run: |
          cd ./terraform
          terraform init
          terraform apply -auto-approve -destroy
