name: Execution dans le Cloud

on: 
  push:
    branches:
      - cloud

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set credentials as environment variable
        run: |
          cd ./cloud
          echo "$CREDENTIALS" > CREDENTIALS.json
          cat CREDENTIALS.json
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          backend-config: '${{ secrets.CREDENTIALS }}'
          working-directory: ./terraform


      - name: Terraform apply
        run: |
          cd ./cloud
          terraform init
          terraform apply -auto-approve -destroy
